### ISSUE TITLE
过不了验证码了

### ISSUE THREAD

**Issue by 2000MAXJ** [1486308032/yuemiao#1]
购买结果 {"code":"9999","msg":"验证失败","data":null,"ok":false,"notOk":true}

**Comment by 1486308032** [comment]
![image](https://user-images.githubusercontent.com/50775291/170214391-5108ce0d-33ae-450c-a9b8-1b1ddbe46fe6.png)
正常预约验证码没有问题。如果是抢购，请自行判断获取验证码的时机（可提前获取验证码，最好要在每分钟的30秒之后获取验证码）。
约苗现在有访问来源检测，请在请求头中加入"referer": "https://wx.scmttec.com/index.html"

**Comment by 2000MAXJ** [comment]
![图片](https://user-images.githubusercontent.com/52954504/170240431-1c2b2d38-4b25-4bcb-8dfe-2b300b5890ba.png)
加有referer了还是不行
![图片](https://user-images.githubusercontent.com/52954504/170240663-3627230d-b658-44b8-90e6-33e6f57ede6f.png)

**Comment by 1486308032** [comment]
\x04是加密坐标的填充文本，详细详细可参考（https://www.jianshu.com/p/d895cff39878），这里是正常的！
验证码的返回结果中：repCODE:0,success:ture表示验证码成功，这里也没问题。
报错是json解析错误，应该是变量__value__ 中的参数没有填写正确导致的。
vaccineCode、linkmanId、subscribeDate、departmentVaccineId等变量值需要自己抓包获取。
head中的tk也需要抓包修改。
main.py文件我修改了一下，修改tk后运行看看，应该是能成功预约的。

**Comment by 2000MAXJ** [comment]
![Uploading 图片.png…]()
 又有新的问题......

**Comment by 1486308032** [comment]
你的图片没上传成功，看不到！
运行程序修改了那些参数，是怎样运行的？
可录屏后，发给我我看看！

**Comment by 2000MAXJ** [comment]
![图片](https://user-images.githubusercontent.com/52954504/170431433-b1041cb6-2f62-4b0a-9c5e-d278a945ffad.png)

**Comment by 1486308032** [comment]
![image](https://user-images.githubusercontent.com/50775291/170467008-fdcad459-39a0-4c6b-b0fc-bba785ee1fd6.png)
![image](https://user-images.githubusercontent.com/50775291/170468047-d445e88b-80d3-4271-9dc4-9f126b16d56b.png)
购买和单独的验证都没问题。main.py修改了一下，重新下载试试。
在程序启动时，修改了哪些参数请详细说明。

**Comment by THE2022** [comment]
![图片](https://user-images.githubusercontent.com/52954504/170721975-cdf5a645-679e-483c-ac9f-e2654e041a4a.png)
 

1. 已解决验证码失效问题
2. 验证码检验时有一定的概率会触发二次请求验证码，从而导致订单失败。。
3. 感谢作者大大！！！！
